### ISSUE TITLE
Bildformat bei 720p 

### ISSUE THREAD

**Issue by taktiker12** [rofafor/vdr-plugin-femon#2]
Danke zuerst für ihren Plugin .
Ich habe festgestellt , dass unter Signalinfo ---> Bildformat keine Info drauf steht wenn ich bein Sendern 720P wie  z.B PhoenixHD , ZDFNEO HD  . andere Sender SD zeigen PAL und 1080i Sender zeigen Component .
Woran es liegt weiss ich net . 
benutze Softhddevice als Ausgabedevice .
Danke

**Comment by rofafor** [comment]
You'll have to add support for those channels into h264.c. Unfortunately, I don't have access such channels and therefore cannot do it  by myself.

**Comment by taktiker12** [comment]
Thank you.
Le 21 févr. 2016 12:31, "Rolf Ahrenberg" notifications@github.com a
écrit :

**Comment by rofafor** [comment]
Most likely those channels don't provide the necessary _video_signal_type_present_flag_ and _video_format_ data in their streams for the detection.

**Comment by taktiker12** [comment]
thank U 4  replay

**Comment by rofafor** [comment]
Verified with arte HD 720p sample that the mentioed fields are missing in the stream and therefore the video format is shown as non-existent.

**Comment by taktiker12** [comment]
This happen with non 5.1 dolby TV channels .
Le 29 févr. 2016 19:46, "Rolf Ahrenberg" notifications@github.com a
écrit :

**Comment by rofafor** [comment]
Please, provide a sample recording for debugging.

**Comment by rofafor** [comment]
Closed due to the inactivity.
