### ISSUE TITLE
SNR/CNR missing satip

### ISSUE THREAD

**Issue by 9000h** [rofafor/vdr-plugin-femon#6]
Hi,
is the not shown CNR unimplented or a bug?
![Screenshot from 2019-11-23 22-40-15](https://user-images.githubusercontent.com/3009073/69485643-a8bfe480-0e42-11ea-8c88-99e1d4526c7e.png)
![Screenshot from 2019-11-23 22-40-44](https://user-images.githubusercontent.com/3009073/69485646-ad849880-0e42-11ea-9d8a-15eb3b0d91e0.png)
CU
9000h

**Comment by rofafor** [comment]
It's not implemented in the satip plugin. Take a look at the `cSatipDevice::SignalStats()`.
